---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-conf-auto
  namespace: default
  labels:
    app: aws-adot-auto
    component: adot-collector-conf-auto
data:
  adot-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318    
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s

          scrape_configs:
          - job_name: 'kubernetes-service-endpoints'

            kubernetes_sd_configs:
            - role: endpoints

            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

            relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_scrape]
              action: keep
              regex: true

    exporters:
      awsxray:
        region: us-east-1
      prometheusremotewrite:
        # replace this with your endpoint
        endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-d345e9f2-d569-490b-baf0-9c380c507c44/api/v1/remote_write"
        auth:
          authenticator: sigv4auth
        namespace: "default"
      logging:
        loglevel: debug

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
      # replace this with your region
      sigv4auth:
        region: "us-east-1"

    service:
      extensions: [pprof, zpages, health_check, sigv4auth]
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          exporters: [logging, prometheusremotewrite]
        traces/1:
          receivers: [otlp]
          exporters: [logging, awsxray]
              
---
# create adot-col service account and role binding
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: amp-iamproxy-ingest-service-account
#  namespace: adot-col
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/amp-iamproxy-ingest-role

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: default
roleRef:
  kind: ClusterRole
  name: adotcol-admin-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: adot-collector-auto
  namespace: default
  labels:
    app: aws-adot-auto
    component: adot-collector-auto
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: adot-collector
  type: NodePort
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: adot-collector-auto
  namespace: default
  labels:
    app: aws-adot-auto
    component: adot-collector-auto
spec:
  selector:
    matchLabels:
      app: aws-adot-auto
      component: adot-collector-auto
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-adot-auto
        component: adot-collector-auto
    spec:
      serviceAccountName: otel-collector
      containers:
      - command:
          - "/awscollector"
          - "--config=/conf/adot-collector-config.yaml"
        image: public.ecr.aws/aws-observability/aws-otel-collector:latest
        name: adot-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP      
        ports:
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 4317
        - containerPort: 4318  
        volumeMounts:
        - name: adot-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: adot-collector-conf-auto
            items:
              - key: adot-collector-config
                path: adot-collector-config.yaml
          name: adot-collector-config-vol
---
